const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const moment = require("moment");

const Lazada = mongoose.model(
  "Lazada",
  new Schema(
    {
      full_label: "String",
      brand: "String",
      voucher_platform: "Number",
      voucher: "Number",
      warehouse_code: "String",
      order_number: "String",
      voucher_seller: "Number",
      created_at: "Date",
      voucher_code: "String",
      gift_option: "Boolean",
      shipping_fee_discount_platform: "Number",
      customer_last_name: "String",
      promised_shipping_times: "String",
      updated_at: "Date",
      price: "Number",
      national_registration_number: "String",
      shipping_fee_original: "Number",
      payment_method: "String",
      customer_first_name: "String",
      shipping_fee_discount_seller: "Number",
      shipping_fee: "Number",
      branch_number: "String",
      tax_code: "String",
      items_count: "Number",
      delivery_info: "String",
      statuses: "Array",
      address_billing: "Array",
      extra_attributes: "String",
      order_id: "String",
      remarks: "String",
      gift_message: "String",
      address_shipping: "Array",
    },
    { timestamps: true }
  ),
  "Lazada"
);

const Lazada_Convert = mongoose.model(
  "Lazada_Convert",
  new Schema(
    {
      full_label: "String",
      brand: "String",
      channel: "String",
      type: "String",
      parent_id: "String",
      voucher_platform: "Number",
      voucher: "Number",
      warehouse_code: "String",
      order_number: "String",
      voucher_seller: "Number",
      created_at: "Date",
      voucher_code: "String",
      gift_option: "Boolean",
      shipping_fee_discount_platform: "Number",
      customer_last_name: "String",
      promised_shipping_times: "String",
      updated_at: "Date",
      price: "Number",
      national_registration_number: "String",
      shipping_fee_original: "Number",
      payment_method: "String",
      customer_first_name: "String",
      shipping_fee_discount_seller: "Number",
      shipping_fee: "Number",
      branch_number: "String",
      tax_code: "String",
      items_count: "Number",
      delivery_info: "String",
      statuses: "Array",
      address_billing: "Array",
      extra_attributes: "String",
      order_id: "String",
      remarks: "String",
      gift_message: "String",
      address_shipping: "Array",
    },
    { timestamps: true }
  ),
  "data_convert"
);

const Lazada_OrderDetail = mongoose.model(
  "Lazada_OrderDetail",
  new Schema(
    {
      full_label: "String",
      brand: "String",
      tax_amount: "Number",
      reason: "String",
      sla_time_stamp: "Date",
      voucher_seller: "Number",
      purchase_order_id: "String",
      voucher_code_seller: "String",
      voucher_code: "String",
      package_id: "String",
      buyer_id: "String",
      variation: "String",
      product_id: "String",
      voucher_code_platform: "String",
      purchase_order_number: "String",
      sku: "String",
      gift_wrapping: "String",
      order_type: "String",
      invoice_number: "String",
      cancel_return_initiator: "String",
      shop_sku: "String",
      is_reroute: "Number",
      stage_pay_status: "String",
      sku_id: "String",
      tracking_code_pre: "String",
      order_item_id: "String",
      shop_id: "String",
      order_flag: "String",
      is_fbl: "Number",
      name: "String",
      delivery_option_sof: "Number",
      order_id: "String",
      fulfillment_sla: "String",
      status: "String",
      product_main_image: "String",
      voucher_platform: "Number",
      paid_price: "Number",
      product_detail_url: "String",
      warehouse_code: "String",
      promised_shipping_time: "String",
      shipping_type: "String",
      created_at: "Date",
      voucher_seller_lpi: "Number",
      shipping_fee_discount_platform: "Number",
      personalization: "String",
      wallet_credits: "Number",
      updated_at: "Date",
      currency: "String",
      shipping_provider_type: "String",
      voucher_platform_lpi: "Number",
      shipping_fee_original: "Number",
      item_price: "Number",
      is_digital: "Number",
      shipping_service_cost: "Number",
      tracking_code: "String",
      shipping_fee_discount_seller: "Number",
      shipping_amount: "Number",
      reason_detail: "String",
      return_status: "String",
      shipment_provider: "String",
      priority_fulfillment_tag: "String",
      voucher_amount: "Number",
      digital_delivery_info: "String",
      extra_attributes: "String",
    },
    { timestamps: true },
    "lazada_order_detail"
  )
);

const Lazada_Detail = mongoose.model(
  "Lazada_Detail",
  new Schema(
    {
      full_label: "String",
      brand: "String",
      channel: "String",
      type: "String",
      parent_id: "String",
      tax_amount: "Number",
      reason: "String",
      sla_time_stamp: "Date",
      voucher_seller: "Number",
      purchase_order_id: "String",
      voucher_code_seller: "String",
      voucher_code: "String",
      package_id: "String",
      buyer_id: "String",
      variation: "String",
      product_id: "String",
      voucher_code_platform: "String",
      purchase_order_number: "String",
      sku: "String",
      gift_wrapping: "String",
      order_type: "String",
      invoice_number: "String",
      cancel_return_initiator: "String",
      shop_sku: "String",
      is_reroute: "Number",
      stage_pay_status: "String",
      sku_id: "String",
      tracking_code_pre: "String",
      order_item_id: "String",
      shop_id: "String",
      order_flag: "String",
      is_fbl: "Number",
      name: "String",
      delivery_option_sof: "Number",
      order_id: "String",
      fulfillment_sla: "String",
      status: "String",
      product_main_image: "String",
      voucher_platform: "Number",
      paid_price: "Number",
      product_detail_url: "String",
      warehouse_code: "String",
      promised_shipping_time: "String",
      shipping_type: "String",
      created_at: "Date",
      voucher_seller_lpi: "Number",
      shipping_fee_discount_platform: "Number",
      personalization: "String",
      wallet_credits: "Number",
      updated_at: "Date",
      currency: "String",
      shipping_provider_type: "String",
      voucher_platform_lpi: "Number",
      shipping_fee_original: "Number",
      item_price: "Number",
      is_digital: "Number",
      shipping_service_cost: "Number",
      tracking_code: "String",
      shipping_fee_discount_seller: "Number",
      shipping_amount: "Number",
      reason_detail: "String",
      return_status: "String",
      shipment_provider: "String",
      priority_fulfillment_tag: "String",
      voucher_amount: "Number",
      digital_delivery_info: "String",
      extra_attributes: "String",
    },
    { timestamps: true },
    "data_convert"
  )
);

const Shopee = mongoose.model(
  "Shopee",
  new Schema(
    {
      full_label: "String",
      brand: "String",
      channel: "String",
      type: "String",
      parent_id: "String",
      checkout_shipping_carrier: "String",
      edt: "Mixed",
      order_chargeable_weight_gram: "Number",
      prescription_check_status: "Mixed",
      reverse_shipping_fee: "Number",
      actual_shipping_fee: "Number",
      actual_shipping_fee_confirmed: "Boolean",
      buyer_cancel_reason: "String",
      buyer_cpf_id: "Mixed",
      buyer_user_id: "String",
      buyer_username: "String",
      cancel_by: "String",
      cancel_reason: "String",
      cod: "Boolean",
      create_time: "Date",
      currency: "String",
      days_to_ship: "Number",
      dropshipper: "Mixed",
      dropshipper_phone: "Mixed",
      edt_from: "Date",
      edt_to: "Date",
      estimated_shipping_fee: "Number",
      fulfillment_flag: "String",
      goods_to_declare: "Boolean",
      item_list: "Array",
      message_to_seller: "String",
      note: "String",
      note_update_time: "Date",
      order_sn: "String",
      order_status: "String",
      package_list: "Array",
      pay_time: "String",
      payment_method: "String",
      pickup_done_time: "Date",
      recipient_address: "Array",
      region: "String",
      ship_by_date: "Date",
      shipping_carrier: "String",
      split_up: "Boolean",
      total_amount: "Number",
      update_time: "Date",
      createDate: "Date",
      order_number: "String",
    },
    { timestamps: true }
  ),
  "Shopee"
);

const Shopee_Convert = mongoose.model(
  "Shopee_Convert",
  new Schema(
    {
      full_label: "String",
      brand: "String",
      channel: "String",
      type: "String",
      parent_id: "String",
      checkout_shipping_carrier: "String",
      edt: "Mixed",
      order_chargeable_weight_gram: "Number",
      prescription_check_status: "Mixed",
      reverse_shipping_fee: "Number",
      actual_shipping_fee: "Number",
      actual_shipping_fee_confirmed: "Boolean",
      buyer_cancel_reason: "String",
      buyer_cpf_id: "Mixed",
      buyer_user_id: "String",
      buyer_username: "String",
      cancel_by: "String",
      cancel_reason: "String",
      cod: "Boolean",
      create_time: "Date",
      currency: "String",
      days_to_ship: "Number",
      dropshipper: "Mixed",
      dropshipper_phone: "Mixed",
      edt_from: "Date",
      edt_to: "Date",
      estimated_shipping_fee: "Number",
      fulfillment_flag: "String",
      goods_to_declare: "Boolean",
      item_list: "Array",
      message_to_seller: "String",
      note: "String",
      note_update_time: "Date",
      order_sn: "String",
      order_status: "String",
      package_list: "Array",
      pay_time: "Date",
      payment_method: "String",
      pickup_done_time: "Date",
      recipient_address: "Array",
      region: "String",
      ship_by_date: "Date",
      shipping_carrier: "String",
      split_up: "Boolean",
      total_amount: "Number",
      update_time: "Date",
      createDate: "Date",
    },
    { timestamps: true }
  ),
  "data_convert"
);

module.exports = {
  Lazada,
  Shopee,
  Lazada_Convert,
  Shopee_Convert,
  Lazada_OrderDetail,
  Lazada_Detail,
};
