const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const TIKTOK_ads = mongoose.model(
  "TIKTOK_ads",
  new Schema(
    {
      brand: "String",
      Date: "Date",
      Advertiser_ID: "String",
      Advertiser_name: "String",
      Campaign_ID: "String",
      Campaign_name: "String",
      Campaign_objective_type: "String",
      Ad_group_ID: "String",
      Ad_group_name: "String",
      Ad_ID: "String",
      Ad_name: "String",
      Video_thumbnail_URL: "String",
      Complete_payment_ROAS_onsite: "Number",
      Complete_payment_onsite: "Number",
      Initiate_checkout_onsite: "Number",
      Product_details_page_view_onsite: "Number",
      Add_to_wishlist_onsite: "Number",
      Add_billing_onsite: "Number",
      Add_to_cart_onsite: "Number",
      Form_submission_onsite: "Number",
      App_store_click_onsite: "Number",
      Total_page_views_onsite: "Number",
      Call_to_Action_button_clicks_onsite: "Number",
      Total_product_clicks_onsite: "Number",
      Complete_payment_ROAS: "Number",
      Complete_payment_events: "Number",
      Total_complete_payment_value: "Number",
      Page_browse_events: "Number",
      Button_click_events: "Number",
      Total_button_click_value: "Number",
      Online_consultation_events: "Number",
      Total_online_consultation_value: "Number",
      User_registrations: "Number",
      Total_user_registration_value: "Number",
      Product_details_page_browse_events: "Number",
      Total_product_details_page_browse_value: "Number",
      Add_to_cart_events: "Number",
      Total_add_to_cart_value: "Number",
      Place_an_order_events: "Number",
      Total_place_an_order_value: "Number",
      Form_submissions: "Number",
      Total_form_submission_value: "Number",
      Download_button_clicks: "Number",
      Total_download_button_click_value: "Number",
      Checkout_initiations: "Number",
      Total_initiate_checkout_value: "Number",
      Add_billing: "Number",
      Total_add_billing_value: "Number",
      Search_events: "Number",
      Total_search_value: "Number",
      Total_subscribe: "Number",
      Total_subscribe_value: "Number",
      Cost_per_subscribe: "String",
      Subscribe_rate__percent: "String",
      Value_per_subscribe: "String",
      VTA_conversions: "Number",
      VTA_registrations: "Number",
      VTA_purchases: "Number",
      CTA_conversions: "Number",
      CTA_registrations: "Number",
      CTA_purchases: "Number",
      Real_time_app_installs: "Number",
      App_installs: "Number",
      Unique_registrations: "Number",
      Unique_purchases: "Number",
      Unique_adds_to_cart: "Number",
      Unique_checkouts: "Number",
      Unique_content_views: "Number",
      Unique_day_2_retentions: "Number",
      Unique_payment_info_additions: "Number",
      Unique_adds_to_wishlist: "Number",
      Unique_app_launches: "Number",
      Unique_tutorial_completions: "Number",
      Unique_group_creations: "Number",
      Unique_group_joins: "Number",
      Unique_role_creations: "Number",
      Unique_credit_spends: "Number",
      Unique_level_achievements: "Number",
      Unique_achievement_unlocks: "Number",
      Unique_in_app_ad_clicks: "Number",
      Unique_in_app_ad_impressions: "Number",
      Unique_loan_applications: "Number",
      Unique_loan_approvals: "Number",
      Unique_loan_disbursements: "Number",
      Unique_logins: "Number",
      Unique_searches: "Number",
      Unique_trial_stats: "Number",
      Unique_subscribes: "Number",
      Registrations_events: "Number",
      Purchase_events: "Number",
      Total_purchase_value: "Number",
      Checkout_events: "Number",
      Total_checkout_value: "Number",
      View_content_events: "Number",
      Total_view_content_value: "Number",
      Day_2_retention_events: "Number",
      Add_payment_info_events: "Number",
      Add_to_wishlist_events: "Number",
      Total_add_to_wishlist_value: "Number",
      Launch_app_events: "Number",
      Complete_tutorial_events: "Number",
      Total_complete_tutorial_value: "Number",
      Create_group_events: "Number",
      Total_create_group_value: "Number",
      Join_group_events: "Number",
      Total_join_group_value: "Number",
      Create_role_events: "Number",
      Total_create_role_value: "Number",
      Spend_credit_events: "Number",
      Total_spend_credit_value: "Number",
      Achieve_level_events: "Number",
      Total_achieve_level_value: "Number",
      Unlock_achievement_events: "Number",
      Total_unlock_achievement_value: "Number",
      In_app_ad_clicks: "Number",
      Total_in_app_ad_click_value: "Number",
      In_app_ad_impressions: "Number",
      Total_in_app_ad_impression_value: "Number",
      Loan_apply_events: "Number",
      Loan_approval_events: "Number",
      Loan_disbursement_events: "Number",
      Login_events: "Number",
      Start_trial_events: "Number",
      Subscribe_events: "Number",
      Unique_generate_lead: "Number",
      Total_generate_lead: "Number",
      Total_generate_lead_value: "Number",
      Unique_rate: "Number",
      Total_rate: "Number",
      Total_rate_value: "Number",
      Profile_visits: "Number",
      Paid_likes: "Number",
      Paid_comments: "Number",
      Paid_shares: "Number",
      Paid_follows: "Number",
      Video_views: "Number",
      two_second_video_views: "Number",
      six_second_video_views: "Number",
      Avg_watch_time_per_video_view: "Number",
      Avg_watch_time_per_person: "Number",
      Video_views_at_25_percent: "Number",
      Video_views_at_50_percent: "Number",
      Video_views_at_75_percent: "Number",
      Video_views_at_100_percent: "Number",
      Impressions: "Number",
      Clicks: "Number",
      CTR: "String",
      Cost: "Number",
      CPC: "String",
      CPM: "String",
      Reach: "Number",
      Frequency: "String",
      Cost_per_1000_people_reached: "String",
      Results: "Number",
      Result_rate: "String",
      Cost_per_result: "String",
      Real_time_results: "Number",
      Real_time_result_rate: "String",
      Cost_per_real_time_result: "String",
      Conversions: "Number",
      Conversion_rate: "String",
      Cost_per_conversion: "String",
      Real_time_conversions: "Number",
      Real_time_conversion_rate: "String",
      Cost_per_real_time_conversion: "String",
      Secondary_goal_result: "String",
      Cost_per_secondary_goal_result: "String",
      createDate: "Date",
      Clicks_All: "Number",
    },
    { timestamps: true }
  ),
  "TIKTOK_ads"
);

const TIKTOK_genderAge = mongoose.model(
  "TIKTOK_genderAge",
  new Schema(
    {
      full_label: "String",
      brand: "String",
      Ad_group_ID: "String",
      Ad_group_name: "String",
      Ad_ID: "String",
      Ad_name: "String",
      Ad_text: "String",
      Advertiser_ID: "String",
      Advertiser_name: "String",
      Age: "String",
      Campaign_ID: "String",
      Campaign_name: "String",
      Campaign_objective_type: "String",
      Data_source: "String",
      Date: "Date",
      Gender: "String",
      Cost: "Number",
      Impressions: "Number",
      Clicks: "Number",
      createDate: "Date",
    },
    { timestamps: true }
  ),
  "TIKTOK_genderAge"
);

module.exports = { TIKTOK_ads, TIKTOK_genderAge };
